# Generated by Django 4.2.16 on 2025-03-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('invoice', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=255)),
                ('booking_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('place', models.CharField(max_length=255)),
                ('consignee_person', models.CharField(max_length=255)),
                ('vehicle_number', models.CharField(max_length=100)),
            ],
        ),
    ]
